(()=>{
    angular
        .module('twitchproject.sug',['ui.router'])
        .config(SuggestionConfig);
    function SuggestionConfig($stateProvider) {
        $stateProvider
            .state('suggestion',{
                url:'/suggestion',
                templateUrl:'/components/suggestion/suggestion.html',
                controller:SuggestionController,
                controllerAs:'ctrl',
                bindToController:this
            })
            .state('suggestions',{
                url:'/suggestions',
                templateUrl:'/components/suggestion/suggestions.html',
                controller:SuggestionsController,
                controllerAs:'ctrl',
                bindToController:this
            });
    }
    SuggestionConfig.$inject=['$stateProvider'];
    function SuggestionController($state,$http,API_BASE) {
        this.submit=()=>{
            $http.post(API_BASE+'suggestions',{sug:this.sug})
            .then((res)=>{
                if(res.data)
                    $state.go('suggestions')
            })
        }
    }
    SuggestionController.$inject=['$state','$http','API_BASE'];
    function SuggestionsController($state,$http,API_BASE) {
        this.delete=(sug,i)=>{
            $http.delete(API_BASE+'suggestions/'+sug)
            .then(res=>{
                if(res.data)
                    this.suggestions.splice(i,1);
            })
            .catch(err=>console.log(err));
        }
        this.suggestions=[];
        $http.get(API_BASE+'suggestions').then(res=>this.suggestions=res.data);
    }
    SuggestionsController.$inject=['$state','$http','API_BASE'];
})();